// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title DenyList — normalized deny list for the SmartAccount (GENERATED).
 * @notice GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Single source of truth: contracts/solidity/testdata/deny-actions.json, itself
 * generated by scripts/sync-deny-list.mjs from the JS canonical sets
 * (packages/chain-eth/src/smart-account.js SELF_ESCALATION_ACTIONS /
 * ALLOWANCE_SURFACE_ACTIONS). The cross-language golden rule: the JS semantic
 * engine and the on-chain SmartAccount must reject the exact same surface, or
 * a variant that JS blocks will slip through on-chain.
 *
 * normalize() mirrors JS normalizeAction (strip whitespace/underscore/dash,
 * lowercase), so any casing/separator variant of a deny action is caught
 * on-chain (INV-005 self-escalation / INV-007 allowance surface).
 */
library DenyList {
    /// Strip whitespace, underscores and dashes; lowercase A-Z.
    /// Mirrors packages/chain-eth/src/smart-account.js normalizeAction.
    function normalize(string calldata value) internal pure returns (bytes memory out) {
        bytes memory b = bytes(value);
        out = new bytes(b.length);
        uint256 n = 0;
        for (uint256 i = 0; i < b.length; i++) {
            uint8 c = uint8(b[i]);
            if (c == 0x20 || c == 0x09 || c == 0x0a || c == 0x0d || c == 0x0b || c == 0x0c || c == 0x5f || c == 0x2d) continue;
            if (c >= 0x41 && c <= 0x5a) c += 0x20;
            out[n++] = bytes1(c);
        }
        assembly ("memory-safe") {
            mstore(out, n)
        }
    }

    /// @return true when `h` (keccak256 of a normalized string) is a isSelfEscalation action.
    function isSelfEscalation(bytes32 h) internal pure returns (bool) {
        if (
            h == keccak256("addowner") ||
            h == keccak256("addrole") ||
            h == keccak256("batch") ||
            h == keccak256("changeemergency") ||
            h == keccak256("changeowner") ||
            h == keccak256("delegate") ||
            h == keccak256("delegatecall") ||
            h == keccak256("destroy") ||
            h == keccak256("executedelegatecall") ||
            h == keccak256("grantrole") ||
            h == keccak256("increaselimit") ||
            h == keccak256("multicall") ||
            h == keccak256("raiselimit") ||
            h == keccak256("removeemergency") ||
            h == keccak256("removeguardian") ||
            h == keccak256("removeowner") ||
            h == keccak256("revokerole") ||
            h == keccak256("rotatesigner") ||
            h == keccak256("selfdestruct") ||
            h == keccak256("setguardian") ||
            h == keccak256("setimplementation") ||
            h == keccak256("setimplementationcode") ||
            h == keccak256("setmaxdaily") ||
            h == keccak256("setmaxpertx") ||
            h == keccak256("setowner") ||
            h == keccak256("setpolicy") ||
            h == keccak256("transferownership") ||
            h == keccak256("updatepolicy") ||
            h == keccak256("upgrade") ||
            h == keccak256("upgradeandcall") ||
            h == keccak256("upgradeto")
        ) return true;
        return false;
    }

    /// @return true when `h` (keccak256 of a normalized string) is a isAllowanceSurface action.
    function isAllowanceSurface(bytes32 h) internal pure returns (bool) {
        if (
            h == keccak256("approve") ||
            h == keccak256("approveandcall") ||
            h == keccak256("createallowance") ||
            h == keccak256("increaseallowance") ||
            h == keccak256("increaseapproval") ||
            h == keccak256("permit") ||
            h == keccak256("permit2") ||
            h == keccak256("setapprovalforall") ||
            h == keccak256("transferfrom")
        ) return true;
        return false;
    }
}
